### ISSUE TITLE
Tolerance values of 'Linear' and 'Single' target blocks inaccessible

### ISSUE THREAD

**Issue by Catreina** [Eniripsa96/SkillAPI#26]
The tolerance values of the 'Target: Linear' and 'Target: Single' options are inaccessible through icon-keys. It seems like they are unable to be modified through attribute modifiers as well.

Sample Code that shows no value for tolerance:
```

Tolerance Test: 
  name: 'Tolerance Test'
  type: ''
  max-level: 1
  skill-req-lvl: 0
  needs-permission: 'false'
  attributes: 
    cost-base: '0'
    cooldown-scale: '0'
    cost-scale: '0'
    level-scale: '0'
    level-base: '0'
    mana-base: '0'
    mana-scale: '0'
    cooldown-base: '0'
  msg: '-'
  icon: 'BEDROCK'
  icon-data: 0
  icon-lore: 
  - ''
  - '   &2Tolerance Test: {attr:GETVALUE.tolerance}'
  - ''
  desc:  []
  components: 
    Initialize: 
      type: 'trigger'
      data: 
        icon-key: ''
      children: 
        Single: 
          type: 'target'
          data: 
            range-scale: '0'
            range-base: '5'
            icon-key: 'GETVALUE'
            wall: 'False'
            tolerance: '4'
            group: 'Enemy'
          children:  {}

```
