### ISSUE TITLE
Hover+Right click on skill slot

### ISSUE THREAD

**Issue by Lix3nn** [Eniripsa96/SkillAPI#269]
Hovering on icon+Right click on skill slot removes skill/emptySlot icon (removes the item completely)
And it comes back as Empty_Slot if youtube hover+right click to that slot again

**Comment by Eniripsa96** [comment]
What is your expectation here, that it comes back with the same skill?

**Comment by Lix3nn** [comment]
Oh is this a feature? I dont want it to disappear, it causes some problems for me

**Comment by Eniripsa96** [comment]
Yeah, skill bars can be customized by right clicking on a slot to toggle between being a skill or item slot. To disable this functionality, look into "config.yml" and change the "layout" option under "Skill Bar" so that all the slots are "locked: true". You'll want it to look something like:

```
  # The default layout for skill bars
  # Players can customize unlocked slots
  layout:
    1:
      skill: true
      locked: true
    2:
      skill: true
      locked: true
    3:
      skill: true
      locked: true
    4:
      skill: true
      locked: true
    5:
      skill: true
      locked: true
    6:
      skill: false
      locked: true
    7:
      skill: false
      locked: true
    8:
      skill: false
      locked: true
    9:
      skill: false
      locked: true
```
