### ISSUE TITLE
[Bug] melee damage & projectile damage still applies even if skillAPI is only enabled in certain world

### ISSUE THREAD

**Issue by signition** [Eniripsa96/SkillAPI#394]
Issue: melee-damage and projectile-damage ( newly added recently ) applies on disabled world.

Reproduction
1. Enable world option in config.yml by doing
```
Worlds: 

  # Whether or not to enable the world restriction
  enable: 'true'
```
and in some world, I will call enabled world as enabledWorld for this bug report

2. make an attribute that increases melee damage in attribute.yml , here is example.
```
physical-melee-attack: 
  display: 'melee damage'
  max: '999'
  icon: 'ink sack'
  icon-data: '14'
  icon-lore: 
  - '&fmelee damage'
  global: 
    condition:  {}
    mechanic: {}
    target:  {}
  stats: 
    melee-damage: 'v*(a*0.3 + 1)'
```

3. make an item that has this attribute in enabledWorld , and test damage. 

4. teleport to some other world, such as "disabledWorld1"

5. try damage something

6. Same damage applies even if it should not ( since skillAPI should be disabled in that world )
