### ISSUE TITLE
For "Suffix can not be null" problem.

### ISSUE THREAD

**Issue by waynechung30330** [Eniripsa96/SkillAPI#86]
Dear All,

I download the newest SkillAPI and MCCore install them. But there are some error appears.

Here is the error message:

> [10:14:59 INFO]: [SkillAPI] Enabling SkillAPI v3.95
> [10:14:59 ERROR]: Failed to copy resource: SkillAPIModule.jar
> [10:14:59 ERROR]: Invalid combo click type: 
> [10:14:59 ERROR]: Invalid combo click type: 
> [10:14:59 ERROR]: Invalid combo click type: 
> [10:14:59 ERROR]: Error occurred while enabling SkillAPI v3.95 (Is it up to date?)
> java.lang.IllegalArgumentException: Suffix cannot be null
> 	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at org.bukkit.craftbukkit.v1_9_R1.scoreboard.CraftTeam.setSuffix(CraftTeam.java:66) ~[craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at com.rit.sucy.scoreboard.BoardManager.updateTeam(BoardManager.java:107) ~[?:?]
> 	at com.rit.sucy.scoreboard.BoardManager.registerTeam(BoardManager.java:95) ~[?:?]
> 	at com.sucy.skill.manager.ClassBoardManager.registerClass(ClassBoardManager.java:131) ~[?:?]
> 	at com.sucy.skill.SkillAPI.addDynamicClass(SkillAPI.java:645) ~[?:?]
> 	at com.sucy.skill.manager.RegistrationManager.initialize(RegistrationManager.java:227) ~[?:?]
> 	at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:130) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346) [craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318) [craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:403) [craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:368) [craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:323) [craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:241) [craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.9.2-R0.1-SNAPSHOT-latest.jar:git-Bukkit-4cb3258]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

Here is my classes.yml:
```
loaded: 'False'
Admin:
  name: 'Admin'
  prefix: '&6Admin'
  group: 'class'
  mana: '&2Mana'
  max-level: '40'
  parent: ''
  needs-permission: 'False'
  mana-regen: '1'
  tree: 'Requirement'
  combo: '0'
  skills:
  - 'Earthquake'
  - 'ArrowTNT'
  icon: 'Potion'
  icon-data: '0'
  icon-lore:
  - '&6Admin'
  - ''
  - '&7The'
  - '&7A!D!M!I!N!'
  attributes:
    health-base: '50.0'
    health-scale: '0.0'
    mana-base: '100.0'
    mana-scale: '0.0'
```

And, my running environment:
Java:  1.8.0_101
Server: CraftBukkit 1.9.2
OS: MacOS X

If here is anyone knows why this happens, please tell me.
Thank you all.

BR.,
Wayne
